language: node_js

os:
  - linux
  - osx

node_js:
  - "0.8"
  - "0.10"
  - "0.12"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"

script:
  - npm run lint
  - npm run codecov

cache:
  directories:
    - "node_modules"

notifications:
  email:
    on_success: never
    on_failure: always
